### ISSUE TITLE
currency command syntax

### ISSUE THREAD

**Issue by justandras** [SwitchbladeBot/switchblade#593] opened 2019-01-20 11:03 UTC
**Bug description**
The current syntax is stupid considering that in the response it's in the other way around

**How to reproduce**
1. Run s!currency HUF  USD 20
2. recive USD -> HUF

**Expected behavior**
recive HUF -> USD but it's still dumb so more stuff: 

Make it like 

> s!currency 20 USD HUF

it would make more sense.  Also it would be great if 

> s!currency USD 20 HUF

would work. 

**Screenshots**
![image](https://user-images.githubusercontent.com/32372119/51438349-51de0180-1cab-11e9-894c-4bcab90195e2.png)

**Additional context**
BOTTOM TEXT

**Comment by Doges** [comment] 2019-01-20 12:12
but if you only put HUF, it will convert to Dollar, and intended behavior, closing issue

**Comment by pedrofracassi** [comment] 2019-01-20 15:14
Intended behaviour, and it was my idea when we were developing that command. I'll reopen it and fix it when I get home.

Assign me.

**Comment by Doges** [comment] 2019-01-20 15:18
PELO AMOR DE SANTO CRISTO, EU JÁ EXPLIQUEI PORQUE NÃO DÁ

**Comment by Doges** [comment] 2019-01-20 15:18
VE A MERDA DO BACK-END DEVELOPERS

**Closed** 2019-02-22 15:38 UTC
Labels: part: commands, type: enhancement, type: idea
