### ISSUE TITLE
Twitter relay

### ISSUE THREAD

**Issue by orisica** [SwitchbladeBot/switchblade#711] opened 2019-02-18 22:14 UTC
Hello,
I would like to propose a feature that follows specified twitter users or even better, specified twitter lists and relays their tweets to a specified discord channel. So basically a twitter feed on discord. Also please make the refresh rate quick, instant would be best if possible.
Thanks

**Comment by metehus** [comment] 2019-02-18 23:29
Can be possible the use of lists and it would be almost instant

**Comment by pedrofracassi** [comment] 2019-02-19 22:55
We could use webhooks or ubsubhubbub

**Comment by dpaiv0** [comment] 2019-02-19 23:12
WebSub (abv. for PubSubHubbub) isn't that great for dev instances. Webhooks should be better, imo.

**Comment by pedrofracassi** [comment] 2019-02-19 23:15
Why wouldn't it? WebSub seems like the way we should do it

**Comment by dpaiv0** [comment] 2019-02-19 23:16
Twitter doesn't support WebSub protocol natively.

**Comment by dpaiv0** [comment] 2019-02-19 23:16
Believe me, I've tried it already

**Comment by pedrofracassi** [comment] 2019-02-19 23:20
What can we use for that then?

**Comment by dpaiv0** [comment] 2019-02-19 23:21
#87

**Comment by pedrofracassi** [comment] 2019-02-19 23:29
Dupe of #87

**Closed by pedrofracassi** 2019-02-19 23:29 UTC
Labels: type: idea, type: new-feature
