### ISSUE TITLE
/bot

### ISSUE THREAD

**Issue by Pasaelpasa** [SwitchbladeBot/switchblade#1398] opened 2022-12-08 23:07 UTC
**Bug description**

**How to reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jpsl00** [comment] 2022-12-08 23:17
Closing as it's most likely a duplicate of #1395

@Pasaelpasa Please provide more details.

**Closed by jpsl00** 2022-12-08 23:17 UTC
