### ISSUE TITLE
DeprecationWarning: ClientUser#setGame: use ClientUser#setActivity instead

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#94] opened 2018-06-05 22:40 UTC
Found today on the console after the latest merge.

**Comment by bolsomito** [comment] 2018-06-05 22:41
Closing this right now as this was caused by me using eval.

**Comment by pedrofracassi** [comment] 2018-06-05 22:41
Baka

**Closed by bolsomito** 2018-06-05 22:41 UTC
Labels: Bug
