### ISSUE TITLE
Hackban command

### ISSUE THREAD

**Issue by perronosaurio** [SwitchbladeBot/switchblade#307] opened 2018-08-14 22:36 UTC

**Comment by Doges** [comment] 2018-08-14 22:36
Dupe of #305

**Closed by Doges** 2018-08-14 22:36 UTC

**Comment by Doges** [comment] 2018-10-25 12:04
![](https://github.trello.services/images/mini-trello-icon.png) [Moderation Commands](https://trello.com/c/06miAEFM/12-moderation-commands)
