### ISSUE TITLE
Warn system for servers

### ISSUE THREAD

**Issue by justandras** [SwitchbladeBot/switchblade#1112] opened 2020-05-20 05:34 UTC
being able to warn users and having a counter that counts their warns, and adding a note to warns that you can get using a command

s!warn pedro not getting out of the bed

**Comment by Doges** [comment] 2020-05-20 11:19
dupe of #1057 :hahaa:

**Closed** 2020-05-20 11:19 UTC

**Comment by pedrofracassi** [comment] 2020-05-20 12:07
> s!warn pedro not getting out of the bed

I'd be banned by now
